### ISSUE TITLE
Error in composing `StructTightACSetTransformation` and `StructCSetTransformation`

### ISSUE THREAD

**Issue by slwu89** [AlgebraicJulia/Catlab.jl#945] opened 2024-10-18 16:15 UTC
Discovered this error from the blog build failing for https://github.com/AlgebraicJulia/Blog/actions/runs/11405769955/job/31739389356 in this block https://github.com/AlgebraicJulia/Blog/blob/master/post/2021/04/cset-graphs-3/index.qmd#L386-L401

Reproducible example below, error is `ERROR: MethodError: no method matching ⋅(::StructTightACSetTransformation{…}, ::Catlab.CategoricalAlgebra.CSets.StructCSetTransformation{…})` on Julia v1.10.5 and Catlab v0.16.18. Error is in the compositions `proj_g₀ ⋅ incl_g` and `proj_h₀ ⋅ incl_h`.

```julia
using Catlab

function box_product(g::T, h::T) where T <: ACSet
  g₀, h₀ = T(nv(g)), T(nv(h))
  incl_g = CSetTransformation((V=vertices(g), E=refl(g)), g₀, g)
  incl_h = CSetTransformation((V=vertices(h), E=refl(h)), h₀, h)
  proj_g₀, proj_h₀ = product(g₀, h₀)
  ob(pushout(pair(proj_g₀ ⋅ incl_g, proj_h₀),
             pair(proj_g₀, proj_h₀ ⋅ incl_h)))
end

n=5
path = path_graph(ReflexiveGraph, n)
path2 = box_product(path, path)
```

**Comment by slwu89** [comment] 2024-10-18 16:18
Full error for completeness:

```julia
julia> path2 = box_product(path, path)
ERROR: MethodError: no method matching ⋅(::StructTightACSetTransformation{…}, ::Catlab.CategoricalAlgebra.CSets.StructCSetTransformation{…})

Closest candidates are:
  ⋅(::ACSetTransformation, ::ACSetTransformation; kwargs...)
   @ Catlab none:0
  ⋅(::GATlab.Syntax.TheoryInterface.WithModel{GATlab.Stdlib.StdTheoryMaps.Maps.PreorderCat.Migrator{var"##default#1023", var"##Leq#1024"}}, ::var"##Leq#1024", ::var"##Leq#1024"; kwargs...) where {var"##default#1023", var"##Leq#1024"}
   @ GATlab none:0
  ⋅(::GATlab.Syntax.TheoryInterface.WithModel{GATlab.Stdlib.StdTheoryMaps.Maps.OpCat.Migrator{var"##Ob#1007", var"##Hom#1008"}}, ::var"##Hom#1008", ::var"##Hom#1008"; kwargs...) where {var"##Ob#1007", var"##Hom#1008"}
   @ GATlab none:0
  ...

Stacktrace:
 [1] box_product(g::ReflexiveGraph, h::ReflexiveGraph)
   @ Main ~/Desktop/misc/tmp.jl:8
 [2] top-level scope
   @ ~/Desktop/misc/tmp.jl:14
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by epatters** [comment] 2024-10-18 18:32
Thanks for the report. I believe the issue is just that (in a breaking change) the meaning of `CSetTransformation` was changed at some point (cc @kris-brown). This code can be fixed by replacing `CSetTransformation` with `ACSetTransformation`:

```julia
using Catlab

function box_product(g::T, h::T) where T <: ACSet
  g₀, h₀ = T(nv(g)), T(nv(h))
  incl_g = ACSetTransformation((V=vertices(g), E=refl(g)), g₀, g)
  incl_h = ACSetTransformation((V=vertices(h), E=refl(h)), h₀, h)
  proj_g₀, proj_h₀ = product(g₀, h₀)
  ob(pushout(pair(proj_g₀ ⋅ incl_g, proj_h₀),
             pair(proj_g₀, proj_h₀ ⋅ incl_h)))
end

n=5
path = path_graph(ReflexiveGraph, n)
path2 = box_product(path, path)
```

That should be enough to fix the blog post. @kris-brown, can you comment on whether anything else needs to be done?

**Comment by kris-brown** [comment] 2024-10-18 18:34
I'd expect Evan's fix to work!

**Comment by epatters** [comment] 2024-10-18 18:36
It does. I tested it :) My question is whether is the missing method *should* be defined. My guess is no: those are two different categories, right?

**Comment by kris-brown** [comment] 2024-10-18 18:38
Yes, exactly, different categories. Of course this will all be much cleaner with the upcoming GATlabification where we can use the same objects and specify explicitly as a parameter which category we wish to compose them in.

**Comment by epatters** [comment] 2024-10-18 18:40
Thanks, makes sense!

**Closed by epatters** 2024-10-18 18:40 UTC
Labels: acsets
